// autogenerated by brownie
// do not modify the existing settings
require("@nomiclabs/hardhat-web3");
require('@primitivefi/hardhat-dodoc');

module.exports = {
  networks: {
    hardhat: {
      hardfork: "london",
      // base fee of 0 allows use of 0 gas price when testing
      initialBaseFeePerGas: 0,
      // brownie expects calls and transactions to throw on revert
      throwOnTransactionFailures: true,
      throwOnCallFailures: true,
      mining: {
        auto: false,
        interval: 12000,
        mempool: {
          order: "fifo",
        },
      },
      chainId: 1,
    },
    awsfork: {
      url: "https://u4ybf5gmfc.execute-api.eu-west-2.amazonaws.com",
    },
  },
  solidity: {
    compilers: [
      {
        version: "0.8.10",
        settings: {
          optimizer: {
            enabled: true,
            runs: 200,
          },
        },
      },
    ],
  },
};
